Кокорин Илья, M3339
itmo2019/task5 pull request #15
Opened 2019-04-07 20:50 UTC by KokorinIlya

2019-04-08 09:02 UTC, rmbaad requested changes

2019-04-08 09:02 UTC, rmbaad commented on src/components/appContent/appContent.css
> +.ApplicationContent__Nav {
Вообще обычно классы пишутся в lowercase, т.е. `.application__nav`. Не критично, но выглядит странно

2019-04-08 09:02 UTC, rmbaad commented on src/components/appContent/appContent.jsx
> +      addLetter: () => {}
Стейт должен быть сериализуемой сущностью, там не должно быть функций

2019-04-08 09:02 UTC, rmbaad commented on src/components/appContent/appContent.jsx
> +              onClick={this.state.addLetter}
this.state это сущность реакта, со своими методами и своим поведением. вносить в неё свои методы точно не стоит

2019-04-08 09:02 UTC, rmbaad commented on src/components/appContent/appContent.jsx
> +                href="../../../public/index.html"
Ссылки можно делать абсолютными путями `/public/index.html`

2019-04-08 09:02 UTC, rmbaad commented on src/components/appContent/appContent.jsx
> +                Спам
Можно вынести названия ссылок в массив и вывести это через map, иначе очень много бесполезной копипасты получается

2019-04-08 09:02 UTC, rmbaad commented on src/components/checkbox/checkbox.css
> +.Checkbox__Input:checked ~ .Checkbox__Box:after {
С реактом подобный подход уже не нужен. Ты можешь скрывать и показывать всё что тебе нужно через стейт и пропсы. Не надо управлять этим через css

2019-04-08 09:02 UTC, rmbaad commented on src/components/checkbox/checkbox.jsx
> +    document.body.querySelector('.Checkbox__Input').checked = false;
Как я говорил в анонсе и в чате, в react нельзя напрямую работать с DOM, всё это должно браться из состояния

2019-04-08 09:02 UTC, rmbaad commented on src/components/letter/letter.jsx
> +    this.state.setCheckedFalse();
Опять же функция в стейте

2019-04-08 09:02 UTC, rmbaad commented on src/components/letter/letter.jsx
> +    function animate() {
Таким образом при каждом перерендере будет создаваться функция animate. Лучше вынести её в свойство класса, а отсюда только вызывать

2019-04-08 09:02 UTC, rmbaad commented on src/components/letter/letter.jsx
> +        return { className: `Letter_Added ${state.className}` };
Не надо класть className в state. Лучше класть туда какой-то флаг, и в зависимости от него генерировать класс. Можно или в рендере или во вспомогательном методе

2019-04-08 09:02 UTC, rmbaad commented on src/components/letterBox/letterBox.jsx
> +      removeLetter: () => {},
Такого в стейте быть не должно

2019-04-08 09:02 UTC, rmbaad commented on src/components/letterDialog/letterDialog.jsx
> +      content: event.target.closest('.Letter').querySelector('.Letter__Topic').textContent
Работа с DOM. Такого быть не должно

2019-04-08 09:02 UTC, rmbaad commented on src/components/lettersList/lettersList.jsx
> +function checkboxAllClicked() {
Понимаю желание просто перенести логику из старой домашки, но в реакте совсем другой подход к разработке приложений, поэтому всё это нужно переписать.
Тебе будет проще, если ты немного переосмыслишь подход. Представь, что ты не можешь ничего делать с DOM, вообще. У тебя есть только состояние в котором хранятся нужные данные (например список писем, у каждого письма есть его информация + отмечено оно или нет), на основе этих данных ты рендеришь компоненты. По разным событиям ты только меняешь состояние благодаря чему у тебя всё перерендеривается так, как ты заранее это заложил в логику компонентов. Это единственный правильный путь и он проще чем этот

2019-04-20 23:41 UTC, KokorinIlya commented
@rmbaad, я переделал, можете посмотреть?

2019-04-23 10:00 UTC, rmbaad approved these changes
В целом ок, но правки надо сделать или здесь или в 6 задании, они важные

2019-04-23 10:00 UTC, rmbaad commented on src/components/app/app.css
> +.header {
Все стили должны находиться в стилях соответствующего компонента. Если это класс header, то он должен быть в header.css внутри компонента Header. Так правильнее и тебе будет удобнее работать с этим в будущем. Ты сразу будешь знать, что если тебе нужно поправить хэдер, то его стили лежат в хэдере, иначе придётся искать по всему проекту (он ведь может быть большим и не таким очевидным)

2019-04-23 10:00 UTC, rmbaad commented on src/components/lettersWindow/lettersWindow.css
> +.contacts {
Опять же, это или должно быть элементом letter-box'а или в отдельном компоненте

2019-04-23 10:00 UTC, rmbaad commented on src/components/lettersWindow/lettersWindow.css
> +.opened-letter {
Похоже на модификатор или отдельный компонент

2019-04-23 10:00 UTC, rmbaad commented on src/components/lettersWindow/lettersWindow.jsx
> +const MAX_MAIL_LIST_SIZE = 5;
30

2019-04-23 10:00 UTC, rmbaad commented on src/components/lettersWindow/lettersWindow.jsx
> +      self.run,
тогда лучше так
```javascript
this.mainTimerId = setTimeout(() => this.run(), getRandomFromRange(MIN_NEW_LETTER_TIMING, MAX_NEW_LETTER_TIMING));
```

2019-04-23 10:00 UTC, rmbaad commented on src/components/navigationBar/navigationBar.jsx
> +          <a className="navigation-bar__item-link" href="/public/index.html">
Опять же, меню лучше сделать на основе данных а не просто сверстать, т.е. взять массив где будут объекты например с ключами text и url, проходишься по ним map'ом и выводишь меню. Не будет копипасты

2019-04-23 10:01 UTC, closed without merging