Бондарчук Юрий, М3335
itmo2019/task5 pull request #16
Opened 2019-04-07 22:59 UTC by YuryBandarchuk16

* Для уменьшения кулдауна на получение нового сообщения можно изменить константу `NEW_EMAIL_COOLDOWN` в `app.jsx`

* Для уменьшения количества писем на странице можно изменить константу `MAX_EMAILS_PER_PAGE` в `app.jsx`

* Для дебага функции `newMail` нужно в функции `render` в `app.jsx` первой строчкой (перед `return`) добавить следующую строчку:

```javascript
window.newMail = this.newMail
```
После этого можно из консоли вызывать `newMail()`

2019-04-08 09:27 UTC, rmbaad requested changes
В целом хорошо, нужно немного поправить

2019-04-08 09:27 UTC, rmbaad commented on package.json
> +    "eslint-config-prettier": "4.1.0",
У npm есть несколько видов зависимостей. dependencies это зависимости которые нужны самому приложению в рантайме, поэтому данный пакет должен быть не в них, а в devDependencies, т.е. в зависимостях, которые нужны для разработки приложения

2019-04-08 09:27 UTC, rmbaad commented on src/app/app.jsx
> +    this.setState(prevState => {
Молодец. Ты понял основную суть

2019-04-08 09:27 UTC, rmbaad commented on src/app/app.jsx
> +          filterText={this.state.filterText}
🔥

2019-04-08 09:27 UTC, rmbaad commented on src/app/app.jsx
> +          <MailScreenWithFooter
Не очень удачное название компонента. `WithFooter` это скорее какое-то его свойство, а в данном случае кажется вообще лишняя информация

2019-04-08 09:27 UTC, rmbaad commented on src/app/components/mail-screen/EMail.jsx
> +                        ${this.props.isUnread ? 'unread' : ''} \
В template strings не нужно ставить \ в конце строки, они тут лишние.
Затея с генерацией верная, но выглядит в компоненте это немного диковато. Лучше хотя бы вынести это в отдельный метод

2019-04-08 09:27 UTC, rmbaad commented on src/app/styles/header/Header.css
> +.search-bar-container {
Не стоит мешать стили для разных компонентов в один файл. В теории, приложение можно оптимизировать и собрать так, чтобы на страницу приезжали только существующие на этой странице компоненты и стили для них. Ну и к тому же поддерживать проще, когда ты чётко знаешь что у тебя есть компонент и в компоненте только его стили, это быстро и удобно

2019-04-08 09:27 UTC, rmbaad commented on src/app/styles/header/Header.css
> +.search-bar-container {
и в других css-файлах тоже

2019-04-08 09:27 UTC, rmbaad commented on src/index.css
> +#container {
Кажется id тут уже совсем не нужен

2019-04-08 17:11 UTC, YuryBandarchuk16 commented
@rmbaad Сделал все необходимые правки!

2019-04-08 17:27 UTC, YuryBandarchuk16 commented
Теперь еще работают кнопки входящие и прочитанные

2019-04-08 20:04 UTC, rmbaad requested changes

2019-04-08 20:04 UTC, rmbaad commented on src/app/components/mail-screen/EmailsList.jsx
> +        allSelected: false
Это точно тут нужно? Не стоит менять стейт в componentDidUpdate т.к. обновление стейта снова вызывает этот метод. Уйдёт в рекурсию

2019-04-08 20:04 UTC, rmbaad commented on src/app/components/mail-screen/EmailsList.jsx
> +          if (this.state.selectedEmailsIDs[emailID] !== false) {
Нельзя так мутировать стейт, только setState, а так же нельзя мутировать стейт в рендере, это вызовет перерендер. Надо унести в более подходящий метод, рендер вызовется сам при изменении стейта

2019-04-08 20:04 UTC, rmbaad commented on src/app/components/mail-screen/EmailsList.jsx
> +          this.setState({
И здесь тоже

2019-04-08 20:04 UTC, rmbaad commented on src/app/styles/left-menu/LeftMenu.css
> +.new-message-btn {
Тут не поправил стиль другого компонента внутри стилей компонента

2019-04-08 20:04 UTC, rmbaad commented on src/app/styles/mail-screen/EMail.css
> +.unread .email__unread-flag {
Лучше унести unread в модификатор элемента

2019-04-08 20:04 UTC, rmbaad commented on src/app/styles/mail-screen/Footer.css
> +.footer-item__link {
Путаница склассами mail-footer__item-link

2019-04-08 20:04 UTC, rmbaad commented on src/app/styles/mail-screen/MailScreen.css
> +.mail-navigation-wrapper {
И тут классы. Смотри, у нас хоть и реакт, но мыслить надо теми же сущностями: блок, элемент и модификатор. Компонент это блок, у него есть элементы. Посторонних блоков в стилях этого блока быть не должно. Если это элемент, нужно его сделать элементом в css, если это другой блок его нужно вынести в отдельный компонент

2019-04-08 20:04 UTC, rmbaad commented on src/app/styles/mail-screen/OpenedEmail.css
> +.close-email {
И здесь

2019-04-08 20:59 UTC, YuryBandarchuk16 commented on src/app/components/mail-screen/EmailsList.jsx
> +          if (this.state.selectedEmailsIDs[emailID] !== false) {
Там выше была создана переменная `selectedEmailsIDs`, которая хранит копию и в которую осуществляется присваивание

2019-04-10 22:50 UTC, YuryBandarchuk16 commented on src/app/components/mail-screen/EmailsList.jsx
> +        allSelected: false
Тут условие есть, что state обновляется, когда allSelected равно `true`, следовательно, рекурсии тут быть не может

Но вообще да, вроде как антипаттерн, но как его избежать?

2019-04-15 13:33 UTC, rmbaad approved these changes

2019-04-15 13:33 UTC, closed without merging