Глухов Евгений, М3337
itmo2019/task5 pull request #24
Opened 2019-05-09 14:57 UTC by AntiFrizz1

Можно добавить сообщение с помощью кнопки "Написать"

2019-05-15 09:51 UTC, rmbaad requested changes

2019-05-15 09:51 UTC, rmbaad commented on src/app/content/content.jsx
> +      lettersIsVisible: true
Кажется что два свойства тут не нужны, т.к. они всегда противоположны. Лучше оставить одно, в один компонент передавать `display={this.state.letterIsVisible}` в другой `display={!this.state.letterIsVisible}`

2019-05-15 09:51 UTC, rmbaad commented on src/app/letter/letter.css
> +#close {
.letter__close

2019-05-15 09:51 UTC, rmbaad commented on src/app/letter/letter.jsx
> +        id="main-letter"
id в Реакте по сути не нужны

2019-05-15 09:51 UTC, rmbaad commented on src/app/letter/letter.jsx
> +        style={{ display: this.props.display ? 'inline-block' : 'none' }}
Инлайн стили не очень хорошо. Лучше генерировать класс и унести это в css

2019-05-15 09:51 UTC, rmbaad commented on src/app/letterHead/letterHead.jsx
> +        id={this.props.id}
Зачем тут id?

2019-05-15 09:51 UTC, rmbaad commented on src/app/letterHead/letterHead.jsx
> +        style={{ display: this.props.isVisible ? 'inline' : 'none' }}
Тоже лучше унести в css

2019-05-15 09:51 UTC, rmbaad commented on src/app/letterHead/letterHead.jsx
> +            id="letter-id-1-checkbox"
И тут id

2019-05-15 09:51 UTC, rmbaad commented on src/app/letters/letters.jsx
> +      <ul className="letters" style={{ display: this.props.display ? 'inline-block' : 'none' }}>
В css

2019-05-15 09:51 UTC, rmbaad commented on src/app/letters/letters.jsx
> +                id={a.id}
id?

2019-05-15 09:51 UTC, rmbaad commented on src/app/letters/letters.jsx
> +        {this.props.letters.map(a => {
Лучше называть переменные понятно. Например letter

2019-05-15 09:51 UTC, rmbaad commented on src/app/letters/letters.jsx
> +                authorName={a.authorName}
Не обязательно передавать каждый пропс отдельно. Можно сделать примерно так `<LetterHead {...a} key={...}`

2019-05-15 09:51 UTC, rmbaad commented on src/app/page/page.jsx
> +    const val1 = val;
Кажется лишнее присваивание

2019-05-15 09:51 UTC, rmbaad commented on src/app/page/page.jsx
> +      const tmp = value;
Тут кажется тоже нет смысла в tmp

2019-05-15 09:51 UTC, rmbaad commented on src/app/page/page.jsx
> +    const tmp = this.state.letters;
`tmp` — так себе название для переменной)

2019-05-15 09:51 UTC, rmbaad commented on src/app/page/page.jsx
> +    const id = `letter-id-${this.state.count}`;
И тут id кажется не нужен

2019-05-15 09:51 UTC, rmbaad commented on src/app/letterHead/letterHead.jsx
> +            type="checkbox"
Есть баг. Если кликнуть рядом с любым чекбоксом (например слева) то отметится первый чекбокс

2019-05-17 19:13 UTC, AntiFrizz1 commented on src/app/page/page.jsx
> +    const val1 = val;
Если его убрать и изменять напрямую val то он ругается

2019-05-17 19:15 UTC, AntiFrizz1 commented on src/app/page/page.jsx
> +      const tmp = value;
Та же ситуация

2019-05-17 19:16 UTC, AntiFrizz1 commented on src/app/page/page.jsx
> +    const id = `letter-id-${this.state.count}`;
id нужен для изменения checkbox'а, а назначение id происходит в этой функции

2019-05-17 19:18 UTC, AntiFrizz1 commented on src/app/letters/letters.jsx
> +                id={a.id}
id нужен чтобы изменять checkbox

2019-05-17 19:19 UTC, AntiFrizz1 commented on src/app/letterHead/letterHead.jsx
> +            id="letter-id-1-checkbox"
label ругается и просит htmlFor

2019-05-18 08:31 UTC, closed without merging