Балашов Ярослав, М3335
itmo2019/task5 pull request #3
Opened 2019-04-06 17:50 UTC by BreakChir

2019-04-20 06:31 UTC, mokhov requested changes
Не всё посмотрел, но уже есть что поправить в следующем задании

2019-04-20 06:31 UTC, mokhov commented on src/components/check/check.jsx
> +    <div className="check">
Лучше не хардкодить, а использовать что-нибудь типа b_

2019-04-20 06:31 UTC, mokhov commented on src/components/check/check.jsx
> +          onChange={isMainCheckBox ? handleCheckAllClick : handleMailCheckClick}
Это нарушение логики, когда часть логики просачивается вне контрола. Сам чекбокс должен уметь только менять состояние, а вот на изменение его состояния должен быть подписан «список писем», который будет решать что делать

2019-04-20 06:31 UTC, mokhov commented on src/components/letter/letter.jsx
> +function LetterItem(props) {
```
function LetterItem(props) {
   const { className, children } = props;
   return <li className={`letter__item ${className}`}>{children}</li>;
}
```

2019-04-20 06:31 UTC, mokhov commented on src/components/letter/letter.jsx
> +      this.setState({ hasAddAnimation: true });
Лучше эту часть унести в функцию с человекочитаемым названием

2019-05-15 20:35 UTC, BreakChir commented on src/components/check/check.jsx
> +    <div className="check">
Не понял про "b_"...

2019-05-23 16:20 UTC, evgenymarkov commented on src/components/check/check.jsx
> +    <div className="check">
Можно воспользоваться библиотеками b_, bem-cn или bem-react/classnames

2019-05-23 16:23 UTC, evgenymarkov commented on src/components/mail/mail.jsx
> +import React from 'react';
Обычно ожидается, что точкой входа будет App

2019-05-23 16:24 UTC, evgenymarkov commented on src/components/mailHeader/mailHeader.css
> +.mail-header {
`mail-header` или `MailHeader`

2019-05-23 16:26 UTC, evgenymarkov commented on src/components/mailHeader/mailHeader.jsx
> +      <Logo className="mail-header__logo" />
Попробуй Figma для редактирования векторной графики

2019-05-23 16:28 UTC, evgenymarkov commented on src/components/letterBox/letterBox.jsx
> +function Hr() {
1 файл - 1 компонент

2019-05-23 16:30 UTC, evgenymarkov commented on src/components/letterBox/letterBox.jsx
> +  MIN_TIMER_ADD_MAIL = 300000;
Не меняются -> static

2019-05-23 16:30 UTC, evgenymarkov commented on src/components/letterBox/letterBox.jsx
> +      curPage: 1,
"Не пиши код впрок" (с)

2019-05-23 16:33 UTC, evgenymarkov commented on src/components/letterBox/letterBox.jsx
> +        <div>
Вёрстка в state – не очень

2019-05-23 16:37 UTC, closed without merging