Дугинец Никита M3337 Hw5
itmo2019/task5 pull request #4
Opened 2019-04-06 19:49 UTC by glcanvas

2019-04-16 07:39 UTC, underoot requested changes
### По функциональности:
* Для разных писем должно открываться разное содержимое письма
* После удаления всех писем галочка "Выделить все" должна быть снята
* Нет анимации при добавлении нового письма
* Нет возможности отметить письмо как прочитанное (после открытия его или по нажатию на кнопку "Прочитано")

### По визуалу:
* Крестик куда-то в письме закрытия уехал к краю текста. Выглядит некрасиво. Желательно поставить его в привычный правый верхний угол
![image](https://user-images.githubusercontent.com/2480721/56187880-9ff56d80-602c-11e9-8bf3-4a30c7ee6874.png)
* В списке ссылок шрифт с засечками надо бы заменить на без засечек
![image](https://user-images.githubusercontent.com/2480721/56187906-b69bc480-602c-11e9-8a00-f0ecac5b01e5.png)
* Маркер прочитанности письма слишком близко к заголовку письма
![image](https://user-images.githubusercontent.com/2480721/56189840-94587580-6031-11e9-9f3c-9d19ec758652.png)
* Футер стесненно прижался к краю контейнера
![image](https://user-images.githubusercontent.com/2480721/56189869-a63a1880-6031-11e9-8942-74a28b5db3e5.png)

2019-04-16 07:39 UTC, underoot commented on src/app/jsx/header.jsx
> +  return (<div className="action-button">
Для балансировки и простоты чтения принято отбивать JSX новой строкой:
```
return (
  <div>
    <main></main>
  </div>
);
```

2019-04-16 07:39 UTC, underoot commented on src/app/jsx/header.jsx
> +    <div className="action-button__line_transparent_height_8px">
Для простоты указания классов в React (да и в любом другом месте) можно воспользоваться [одной](https://www.npmjs.com/package/bem-cn) [из](https://www.npmjs.com/package/b_) [библиотек](https://www.npmjs.com/package/@bem-react/classname) для указания BEM-сущности

2019-04-16 07:39 UTC, underoot commented on src/app/jsx/header.jsx
> +    <div className="action-button__line_black">
Набирать линии можно более просто, например циклом, поскольку JSX — это же и JavaScript, а значит свою жизнь можно немного облегчить и не набирать и не перечислять повторяющиеся (чередующиеся) узлы

2019-04-16 07:39 UTC, underoot commented on src/app/jsx/header.jsx
> +export class MailHeader extends Component {
А почему здесь оставил класс?

2019-04-16 07:39 UTC, underoot commented on src/app/jsx/main.jsx
> +          <button className="menu__action-button text_hide-by-size">Входящие</button>
Кнопку с данным модификатором можно вынести в отдельный компонент, чтобы не повторять название класса

2019-04-16 07:39 UTC, underoot commented on src/app/jsx/main.jsx
> +          <button className="menu__action-button text_hide-by-size" onClick={this.props.addNewLetter}>ДОБАВИТЬ
Верхний регистр текста кнопки можно вынести в стиль `text-decoration: uppercase`. Это больше относится к стилизации, нежели чем к данным (в смысле тексту)

2019-04-16 07:39 UTC, underoot commented on src/app/jsx/main.jsx
> +function TemplateMail(props) {
Это уже скорее не шаблон, а просто компонент `Mail`. В React любой компонент (кроме, безусловно статичных) — это шаблон от данных

2019-04-16 07:39 UTC, underoot commented on src/app/jsx/main.jsx
> +    this.addNewMailBuClick();
Вероятно опечатка — `byClick`

2019-04-16 07:39 UTC, underoot commented on src/app/jsx/main.jsx
> +class MailsAction extends Component {
Компонент стоит именовать более привязанным, так скажем, к контексту использования более конкретному стоит. Здесь нейминг `Action` довольно абстрактный и без просмотра что там рендерится — сложно понять, что это такое. Именование должно говорить само за себя. К примеру, `MailsToolbar`

2019-04-16 07:39 UTC, underoot commented on src/app/jsx/main.jsx
> +class MainMenu extends Component {
Стоит придерживаться правилу — один модуль это один компонент. Структурированный таким образом код затем сложнее читать и поддерживать, чем один модуль — простыню из компонент

2019-04-16 07:39 UTC, underoot commented on src/app/jsx/main.jsx
> +  deleteSelected = (e) => {
Стоит использовать обычные методы класса, которые в конструкторе просто биндятся к своему контексту:
```
contructor(...args) {
  super(...args);
  this.deleteSelected = this.deleteSelected.bind(this);
}

2019-04-16 07:39 UTC, underoot commented on src/app/jsx/main.jsx
> +  constructor(props) {
А зачем пустой конструктор?

2019-04-16 07:39 UTC, underoot commented on src/app/jsx/main.jsx
> +            <input className="mails-checkbox__checkbox" onChange={selectAll} type="checkbox"/>
Методы стоит держать в компоненте, или в пропсах

2019-04-16 07:39 UTC, underoot commented on src/app/jsx/main.jsx
> +  let checkBox = document.querySelectorAll("[data-checkbox-select]");
Такого следует избегать. React — мощная библиотека, которая реализует под капотом паттерн [Model-View-ViewModel](https://en.wikipedia.org/wiki/Model–view–viewmodel) (MVVM), а это значит, что теперь не нужно руками поддерживать состояние всех HTML-элементов. Достаточно где-то в одном из _умных_ компонент поддерживать актуальный _state_ приложения и синхронизировать его, принимая события от UI-компонент. К примеру, в данном случае состояние выбрано письмо или нет можно вынести в _state_, передавать состояние во все письма ниже, а при клике на чекбокс выделения всего обновлять _state_ (менять состояние всех)

2019-04-16 07:39 UTC, underoot commented on src/app/jsx/main.jsx
> +const randomDate = (start, end) => {
Такие хелперы лучше содержать в отдельном модуле

2019-04-16 07:39 UTC, underoot commented on src/app/jsx/main.jsx
> +      className={props.cls ? "mail mail_status_not-read delete-animation " + props.cls : "mail mail_status_not-read"}
Лучше поддерживать сквозной с React нейминг, т.е. оставить `className`

2019-04-16 07:39 UTC, underoot commented on src/app/jsx/main.jsx
> +      className={props.cls ? "mail mail_status_not-read delete-animation " + props.cls : "mail mail_status_not-read"}
А что это за логика? При передаче класса из списка классов пропадает `delete-animation`?

2019-04-16 07:39 UTC, underoot commented on src/app/jsx/main.jsx
> +    let mail = {
Можно создать отдельный класс письма. Очень сложная генерация нового объекта намекает на то, что логику создания следует инкапсулировать для дальнейшего простого использования

2019-04-16 07:39 UTC, underoot commented on src/app/jsx/main.jsx
> +                  return <TemplateMail id={mail.id} image={mail.image} title={mail.title} text={mail.text}
Для элемента в списке следует поддерживать его идентификатор [`key`](https://reactjs.org/docs/lists-and-keys.html#keys)

2019-04-16 07:39 UTC, underoot commented on src/app/jsx/main.jsx
> +                if (mail.delete === false) {
Вместо развилки можно просто передавать этот признак в компонент, а он будет принимать решение добавлять класс `delete-animation` в зависимости от этого признака, или нет

2019-04-16 07:39 UTC, underoot commented on src/app/jsx/main.jsx
> +        <MainMenu addNewLetter={this.addNewMailBuClick.bind(this)}/>
Биндить метод следует в конструкторе, а то ты при каждом рендере создаешь новый инстанс этого метода

2019-04-16 07:39 UTC, underoot commented on src/app/jsx/main.jsx
> +          {this.state.plaseholder ? <PreviewPlaceholder closeClick={this.hidePlaceholders}/> :
Можно отображать при клике содержимое письма через [`Portal`](https://reactjs.org/docs/portals.html) и делать это для каждого письма

2019-04-16 07:39 UTC, underoot commented on src/app/jsx/main.jsx
> +            <div id="mails-placeholder" className="list-of-mails" onClick={this.showMailContent}>
Подозрительно общий на всех `onClick`

2019-04-16 07:39 UTC, underoot commented on src/app/jsx/main.jsx
> +      let plaseholder = !state.plaseholder;
Вероятно опечатка —  `placeholder`

2019-04-16 07:39 UTC, underoot commented on src/app/jsx/main.jsx
> +            <div id="mails-placeholder" className="list-of-mails" onClick={this.showMailContent}>
Кстати, здесь паттерном _Event delegation_ можно пренебречь. React сам аггрегирует события в одном общем контейнере верхнем, поэтому события можно вешать не на весь список, а на конкретные элементы

2019-04-16 07:39 UTC, underoot commented on src/app/jsx/main.jsx
> +        } else {
Можно без `else`. Все равно из первой ветки предварительно выходишь

2019-04-16 07:39 UTC, underoot commented on src/app/jsx/main.jsx
> +          let tmp = item;
По сути, ссылку на объект ты забиндил на новый идентификатор. Если хочешь полностью склонировать объект, то можешь сделать так:
```
let tmp = Object.assign({}, item);
```
или, используя синтаксис ES.Next:
```
let tmp = {...item}
```

Главное помнить, что это работает только для одного уровня вложенности

2019-04-16 07:39 UTC, underoot commented on src/app/jsx/main.jsx
> +      let mails = state.mails;
Для пущей иммутабельности стоит сделать `[...state.mails]`, а иначе ты модифицируешь предыдущее состояние

2019-05-02 10:51 UTC, glcanvas commented on src/app/jsx/header.jsx
> +export class MailHeader extends Component {
т.к. класс импортился без слова `export` (ага, сначала пишу потом думаю...), fixed

2019-05-03 09:58 UTC, glcanvas commented
@underoot  поправил

2019-05-16 22:41 UTC, underoot requested changes

2019-05-16 22:41 UTC, underoot commented on src/app/jsx/componetns.jsx
> +import {Component} from "react";
В названии файла опечатка — `componetns`

2019-05-16 22:41 UTC, underoot commented on src/app/jsx/componetns.jsx
> +    console.log("hmmm" + " " + this.props.animate);
Отладку можно и убрать

2019-05-16 22:41 UTC, underoot commented on src/app/jsx/componetns.jsx
> +      this.node.current.classList.add("mail_offset-40px");
Зачем так, ведь есть же `props` и возможность указывать `className` у элемента

2019-05-16 22:41 UTC, underoot commented on src/app/jsx/componetns.jsx
> +export class Mail extends Component {
Хорошо бы все-таки каждый компонент положить в отдельный модуль

2019-05-16 22:41 UTC, underoot commented on src/app/jsx/main.jsx
> +      state['mails'] = mails;
Лучше придерживаться единого стиля и оставить _dot notation_

2019-05-16 22:41 UTC, underoot commented on src/app/scripts/init-global-vars.js
> +export const findMail = (element) => {
Не используется

2019-05-16 22:41 UTC, underoot commented on src/app/jsx/main.jsx
> +} from '../scripts/init-global-vars';
Название модуля явно стало не актуальным. Переменные не глобальные.

2019-05-16 22:41 UTC, underoot commented on src/app/jsx/header.jsx
> +import '../styles/main.css';
Для того, чтобы проще поддерживать стили — их стоит импортировать у модуля соответствующего компонента

2019-05-16 22:41 UTC, underoot commented on src/app/jsx/main.jsx
> +      state['mails'] = state.mails.filter((item) => item.id.toString() !== id.toString());
Нужно не мутировать предыдущий стейт, а вернуть полностью новый (или его часть). В данном случае ты мутируешь свойство предыдущего стейта — `state.mails`

2019-05-16 22:41 UTC, underoot commented on src/app/jsx/main.jsx
> +    if (target === undefined || target.getAttribute("data-delete") === null) {
Не стоит манипулировать `data`-аттрибутами в React. Следует хранить все статусы и данные в стейте.

2019-05-16 22:41 UTC, underoot commented on src/app/jsx/main.jsx
> +              <div id="mails-placeholder" className="list-of-mails">
Зачем тут айдишник?

2019-05-16 22:46 UTC, underoot commented
Нет ограничение на единовременное отображение в списке только 30 писем

2019-05-17 06:21 UTC, glcanvas commented on src/app/jsx/main.jsx
> +    let mails = this.state.mails.filter((item, index) => index < 30);
@underoot  есть ограничение
но я вывожу 30 самых последних

2019-05-17 07:51 UTC, underoot commented on src/app/jsx/main.jsx
> +    let mails = this.state.mails.filter((item, index) => index < 30);
Это хорошо, но еще лучше не ходить по массиву, а просто его slice-нуть

2019-05-17 07:51 UTC, underoot commented on src/app/jsx/main.jsx
> +    let mails = this.state.mails.filter((item, index) => index < 30);
Еще переменную, как константу, желательно вынести либо сюда наверх, либо в отдельный файл с константами

2019-05-17 18:29 UTC, glcanvas commented on src/app/jsx/componetns.jsx
> +      this.node.current.classList.add("mail_offset-40px");
так не пойдет т.к. будет создано во время монтажа и тогда не будет анимации, поэтому выбрал такое решение

2019-05-17 19:36 UTC, glcanvas commented on src/app/jsx/main.jsx
> +    if (target === undefined || target.getAttribute("data-delete") === null) {
но он нужен что бы понять что это есть место куда можно жать что бы показать содержимое письма, он никак не меняется. 
Вообще как говорилось ранее можно везде навесить листенер, но тогда получится много избыточного кода что будет выглядеть неочень

2019-05-17 19:44 UTC, glcanvas commented
@underoot поправил, посмотрите, пожалуйста

2019-05-18 07:51 UTC, underoot approved these changes

2019-05-18 08:01 UTC, closed without merging