Куриленко Влад, М3337
itmo2019/task5 pull request #7
Opened 2019-04-06 20:29 UTC by MadHypnofrog

пока есть только базовый дизайн, функциональность WIP

2019-04-16 09:39 UTC, underoot requested changes
* Заголовок приложения стоит сменить с _React App_ на, например _Яндекс.Почта_ 

### По функциональности:
* Не работает выделение и нажатие на кнопку "Прочитано" для отметки письма как прочитано.
* После удаления большого числа писем происходит зависание приложения. Думаю это вызвано встающими в очередь обработчиками удаления писем после `transitionend`. Попробуй убрать два списка и упростить операцию удаления, таким образом

2019-04-16 09:39 UTC, underoot commented on src/body/lettersFooter.jsx
> +    return  <div className="letters__options_footer_wrapper">
Стоит выровнять отступы

2019-04-16 09:39 UTC, underoot commented on src/body/letters.jsx
> +            selectAllLetters: undefined,
Вместо `undefined` лучше явно использовать `null`, а иначе (без инспекции аттрибутов свойства не понять есть ли свойство в объекте или нет)

2019-04-16 09:39 UTC, underoot commented on src/body/letters.jsx
> +    setSelectAll = (fun) => {
Кажется, что здесь некоторые проблемы с композицией. Не следует модифицировать стейт верхнего компонента через дочерние компоненты. Необходимо функциональность передавать сверху вниз — не более того. В случае с данным методом (как и, впрочем, с остальными, передаваемыми в `LettersLetterbox `) — стоит передавать его явно из Letters вниз и хранить как просто методы `Letters`, а не часть его состояния. Состояние чаще всего — это именно состояние, не поведение.

2019-04-16 09:39 UTC, underoot commented on src/body/letterbox.jsx
> +			state.displayedMessages[messageID].checked = !state.displayedMessages[messageID].checked
Стоит не забывать, что объекты в JavaScript — мутабельны. Это значит, что в данной строке ты модифицировал предыдущий стейт. Следует явно создать новый объект. Например так:
```
this.setState(state => ({
  displayedMessages: {
      ...state.displayedMessages,
     [messageID]: {
       ...state.displayedMessages[messageID],
      checked: true // or false
     }
  },
})
```

2019-04-16 09:39 UTC, underoot commented on src/body/letterbox.jsx
> +			state.displayedMessages[messageID].checked = !state.displayedMessages[messageID].checked
Это касается и остальных мест модификации стейта

2019-04-16 09:39 UTC, underoot commented on src/body/letterbox.jsx
> +		return  <LetterTemplate
Это скорее не `LetterTemplate`, а просто `Letter`. В React любой компонент (кроме, разумеется, статичных) по сути своей является шаблоном

2019-04-16 09:39 UTC, underoot commented on src/body/letterbox.jsx
> +			if (state.displayedMessages.length > this.MAX_MESSAGES) {
Можно просто отображать в методе `render` первые 30 писем и все. Второй список не нужен

2019-04-16 09:39 UTC, underoot commented on src/body/letterbox.jsx
> +	sendMessage = () => {
Генератор новых писем можно вынести в отдельную сущность со своим отдельным модулем и здесь ее только использовать. Компонент сейчас получается довольно большим и сложным

2019-04-16 09:39 UTC, underoot commented on src/body/letterbox.jsx
> +			var messageID = Array.prototype.indexOf.call(state.displayedMessages,
А зачем ты используешь через `.call` метод прототипа массива над массивом?

2019-04-16 09:39 UTC, underoot commented on src/template/letter.jsx
> +			this.ref.current.addEventListener('transitionend', (event) => {
Стоит [избегать действий](https://reactjs.org/docs/react-component.html#render) и side-эффектов в методе `render`.
> The render() function should be pure, meaning that it does not modify component state, it returns the same result each time it’s invoked, and it does not directly interact with the browser.

Следует перенести это дело, к примеру в `componentDidUpdate` например

2019-04-16 09:39 UTC, underoot commented on src/template/letter.jsx
> +	    return  <div className={`letters__single_letter
Для простоты указания классов в React (да и в любом другом месте) можно воспользоваться [одной](https://www.npmjs.com/package/bem-cn) [из](https://www.npmjs.com/package/b_) [библиотек](https://www.npmjs.com/package/@bem-react/classname) для указания BEM-сущности

2019-04-16 09:39 UTC, underoot commented on src/template/letter.jsx
> +	                		onChange={() => this.props.uncheckSelectAllCheckbox(id)}></input>
Название метода уже определяет реакцию, а не событие-обработчик. Стоит придерживаться принципа универсальности. Возможно потом изменение состояние этого чекбокса приведет не только к отключению чекбокса, отвечающего за состояние всех чекбоксов, а будет и к другим эффектам и изменениям

2019-04-19 21:46 UTC, MadHypnofrog commented on src/body/lettersFooter.jsx
> +    return  <div className="letters__options_footer_wrapper">
починил, но это не точно, у меня изначально выглядело вроде все нормально

2019-04-19 21:47 UTC, MadHypnofrog commented on src/body/letters.jsx
> +            selectAllLetters: undefined,
поменял

2019-04-19 22:15 UTC, MadHypnofrog commented on src/body/letters.jsx
> +    setSelectAll = (fun) => {
кажется, что без модификации стейта родителя из детей вообще будет невозможно тогда делать - например, если я выношу newMail из Letterbox в Letters, чтобы спокойно передать его вниз в него и в LettersOptions, то мне придется вынести и весь функционал по работе с письмами, в частности, список писем; затем мне придется и его передавать в Letterbox, но вот как раз из него мне иногда нужно менять письма (например, при нажатии на чекбокс помечать в эррэе с письмами, что письмо отмечено). вот эта ссылка https://reactjs.org/docs/lifting-state-up.html тоже говорит, что передавать детям хэндлеры, которые изменяют состояние родителя, это норма. переделал на такое

2019-04-19 22:50 UTC, MadHypnofrog commented on src/body/letterbox.jsx
> +			state.displayedMessages[messageID].checked = !state.displayedMessages[messageID].checked
такой способ у меня почему-то переводил Array в Object, и по итогу было не оч хорошо, сделал просто через копии

2019-04-19 23:10 UTC, MadHypnofrog commented on src/body/letterbox.jsx
> +			if (state.displayedMessages.length > this.MAX_MESSAGES) {
сделал через slice везде

2019-04-19 23:11 UTC, MadHypnofrog commented on src/body/letterbox.jsx
> +		return  <LetterTemplate
да, поменял

2019-04-19 23:12 UTC, MadHypnofrog commented on src/body/letterbox.jsx
> +			var messageID = Array.prototype.indexOf.call(state.displayedMessages,
потому что когда-то давно у меня оно работало только так, хз что было не так, поменял обратно

2019-04-19 23:20 UTC, MadHypnofrog commented on src/body/letterbox.jsx
> +	sendMessage = () => {
вынес Message в отдельный файл

2019-04-19 23:22 UTC, MadHypnofrog commented on src/template/letter.jsx
> +			this.ref.current.addEventListener('transitionend', (event) => {
отнес, вроде не поломалось ничего

2019-04-19 23:24 UTC, MadHypnofrog commented on src/template/letter.jsx
> +	                		onChange={() => this.props.uncheckSelectAllCheckbox(id)}></input>
немного не понял сути, если вдруг поведение изменится, ничего не помешает дописать в функцию после uncheckSelectAllCheckbox еще какой-нибудь функционал и все будет норм, а на данный момент явно видно что происходит при нажатии чекбокса

2019-04-20 00:05 UTC, MadHypnofrog commented
кнопку прочитано впилил, ее раньше не было прост
удаление поменял чутка, транзишнов действительно было много т.к. они вешались каждый раз при перерендере или при обновлении компоненты, внес ref внутрь письма, теперь листенер проставляется один раз и все норм
название тож поменял

2019-04-20 01:31 UTC, MadHypnofrog commented on src/template/letter.jsx
> +	    return  <div className={`letters__single_letter
что-то подобавлял

2019-05-16 22:00 UTC, underoot commented on src/body/index.js
> +import bodyWrapper from './body'
Можно делать
```
export { default } from './body';
```

2019-05-16 22:00 UTC, underoot commented on src/body/letters.jsx
> +            var messageID = state.messages.indexOf(state.messages.find(elem => elem.ID === messageKey))
Можно сделать проще с помощью `.filter`

2019-05-16 22:02 UTC, underoot commented on src/body/letters.jsx
> +const b = block('letters')
Можно здесь `export const b ...`

2019-05-16 22:09 UTC, underoot approved these changes

2019-05-16 22:09 UTC, closed without merging